# Generated by Django 5.0.1 on 2024-01-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0058_remove_review_review_text_review_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('residential_address', models.TextField()),
                ('national_id', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
    ]
