# Generated by Django 5.0.1 on 2024-01-29 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0060_deliveryagent_is_approved_deliveryagent_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryAgent',
        ),
    ]
