# Generated by Django 5.0.1 on 2024-01-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0062_deliveryagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
        ),
    ]
