# Generated by Django 5.0.1 on 2024-01-30 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0063_deliveryagent_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
