# Generated by Django 5.0.1 on 2024-01-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0064_deliveryagent_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryagent',
            name='user',
        ),
    ]
