# Generated by Django 5.0.1 on 2024-01-30 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0066_deliveryagent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='vechicle_type',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
