# Generated by Django 5.0.1 on 2024-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0067_deliveryagent_vechicle_type_alter_deliveryagent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
