# Generated by Django 5.0.1 on 2024-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0068_alter_deliveryagent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
