# Generated by Django 5.0.1 on 2024-01-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0069_alter_deliveryagent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
