# Generated by Django 5.0.1 on 2024-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecohiveapp', '0074_alter_deliveryagent_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagent',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='not_available', max_length=15),
        ),
    ]
